import React, { useState } from "react";
import { useRouter } from "next/router";
import FormData from "form-data";
import axios from "axios";
import cookie from "js-cookie";
import Head from "next/head";
import LoginregisterLayout from "../../layout/loginregisterLayout";
import CategoryCard from "../../components/categoryCard";
import InputBox from "../../components/inputBox";
import Link from "next/link";
import { ToastContainer, toast } from "react-toastify";

export default function Login() {
  const router = useRouter();
  const API = process.env.NEXT_PUBLIC_API_ENDPOINT;
  const [userData, setUserData] = useState({
    user_email: "",
    user_password: "",
    user_role: "",
  });
  const [attention, setAttention] = useState(false);
  const handleAttention = () => setAttention(true)

  const notify = (title) =>
  toast.error(title, {
    position: "top-center",
    autoClose: 2500,
    hideProgressBar: false,
    closeOnClick: true,
    pauseOnHover: true,
    draggable: true,
    progress: undefined,
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    const data = new FormData();
    data.append("user_email", userData.user_email);
    data.append("user_password", userData.user_password);
    // data.append("user_role", Number(userData.user_role));

    try {
      const res = await axios({
        method: "post",
        url: `${API}/users/login`,
        data: data,
        headers: {
          "Content-Type": `multipart/form-data`,
        },
      });
      cookie.set("token", res.data.token)
      if(res.data.role_id == 1){
        router.replace("/seller");
      }else if(res.data.role_id == 2){
        router.replace("/"); 
      }else if(res.data.password == "incorect"){
        handleAttention()
      }else if(res.data.user == null){
        notify("User tidak tersedia, silahkan daftar")
      }
      
    } catch (error) {
      console.log(error.response);
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setUserData({ ...userData, [name]: value });
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginregisterLayout>
        <h3 className="fw-bold mb-3 pb-3" style={{ letterSpacing: "1px" }}>
          Masuk
        </h3>
        <form onSubmit={handleSubmit} style={{ maxWidth: "600px" }}>
          <div className="col-12 mt-2">
            <label>Email</label>
            <InputBox
              type="email"
              name="user_email"
              className="form-control mt-2"
              placeholder="Contoh: johndee@gmail.com"
              onChange={(e) => handleChange(e)}
            />
          </div>

          <div className="col-12 mt-2">
            <label>Password</label>
            <InputBox
              type="password"
              name="user_password"
              onChange={(e) => handleChange(e)}
              className="form-control mt-2"
              placeholder="Masukkan password"
            />
            {attention == true && (
              <p className="mt-1" style={{color: "red"}}>Password salah, silahkan coba kembali</p>
            )}
            
          </div>
          <div className="mt-4 mb-4 text-center fw-bold">
            <div className="start-0 end-0 d-flex">
              <CategoryCard
                type="submit"
                className="p-3 flex-grow-1"
                text="Masuk"
                rad="16"
              />
            </div>
          </div>
        </form>
        <h5 className="d-flex justify-content-center">
          Belum punya akun?&nbsp;
          <Link href={"/account/register"}>
            <a style={{ color: "var(--purple)", textDecoration: "none" }}>
              Daftar disini
            </a>
          </Link>
        </h5>
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          toastStyle={{backgroundColor: "#7126B5", color: "white"}}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
      </LoginregisterLayout>
    </>
  );
}
