/* eslint-disable @next/next/no-html-link-for-pages */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @next/next/no-sync-scripts */
import React from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import FormRegister from "../../components/formregister";
import LoginregisterLayout from "../../layout/loginregisterLayout";

import useResize from "../../hooks/useResize";

export default function Login() {

  const screen = useResize();

  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossorigin="anonymous"
        ></script>
      </Head>


      <LoginregisterLayout>


        {screen.md ? (
          <div className="d-flex align-items-center"
            style={{ marginTop: "100px" }}>
            <div className="col-6 offset-3 mt-3 d-flex flex-column justify-content-center">
              <FormRegister />
              <h1 className={styles.title}>
                Sudah punya akun? <a href="/login">Masuk di sini</a>
              </h1>
            </div>
          </div>


        ) :
          (
            <div className="px-3 mt-5">
              <FormRegister />
              <div className="mb-5 px-3 fixed-bottom justify-content-center" style={{ marginBottom: "0px" }}>
                <h1 className={styles.title}>
                  Sudah punya akun? <a href="/login">Masuk di sini</a>
                </h1>
              </div>
            </div>

          )}



      </LoginregisterLayout>
    </>
  );
}
