/* eslint-disable @next/next/no-html-link-for-pages */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @next/next/no-sync-scripts */
import React from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import LoginregisterLayout from "../../layout/loginregisterLayout";

export default function Register() {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossorigin="anonymous"
        ></script>
      </Head>

      <LoginregisterLayout>
        <div className={styles.login}>
          <form style={{ width: "23rem" }}>
            <h3 className="fw-bold mb-3 pb-3" style={{ letterSpacing: "1px" }}>
              Daftar
            </h3>

            <div className="form-outline mb-4">
              <label className="form-label" htmlFor="name">
                Nama
              </label>
              <input
                type="text"
                id="name"
                placeholder="Nama Lengkap"
                className="form-control form-control-lg"
              />
            </div>

            <div className="form-outline mb-4">
              <label className="form-label" htmlFor="form2Example18">
                Email
              </label>
              <input
                type="email"
                id="form2Example18"
                placeholder="Contoh: johndee@gmail.com"
                className="form-control form-control-lg"
              />
            </div>

            <div className="form-outline mb-4">
              <label className="form-label" htmlFor="form2Example28">
                Password
              </label>

              <input
                type="password"
                id="form2Example28"
                placeholder="Masukkan password"
                className="form-control form-control-lg"
              />
            </div>

            <div className="pt-1 mb-4 text-center">
              <button
                className="btn btn-lg btn-block text-center"
                type="submit"
              >
                Daftar
              </button>
            </div>
            <h5 className="text-center">
              Sudah punya akun? <a href="/login">Masuk di sini</a>
            </h5>
          </form>
        </div>
      </LoginregisterLayout>
    </>
  );
}
