/* eslint-disable @next/next/no-html-link-for-pages */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @next/next/no-sync-scripts */
import React from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Search from "../../components/search";

import CategoryCard from "../../components/categoryCard";
import ProdukDesktopLayout from "../../layout/produkDesktop";
import ProdukHomeLayout from "../../layout/produkHome";

export default function Tes() {
    return (
        <>
            <Head>
                <title>tes</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <script
                    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                    crossorigin="anonymous"
                ></script>
            </Head>

            <ProdukHomeLayout />



        </>
    );
}
