import React, {useState} from "react";
import { GetToken } from "../../utils/getToken";
import axios from "axios";
import MobileLayout from "../../layout/mobileLayout";
import Link from "next/link";
import moment from "moment";
import Head from "next/head";
const API = process.env.NEXT_PUBLIC_API_ENDPOINT;

export async function getServerSideProps(context) {
    let user = null;
    let allcookie = context.req.headers.cookie || "   ";
    let token = GetToken(allcookie);
    let carts = [];
    let notifications = []
    
    try {    
        const res_user = await axios({
            method: `get`,
            url: `${API}/users`,
            headers: {
              Authorization: `Bearer ${token}`,
            },
        });
        user = res_user.data.data;

        const res_cart = await axios({
            method: `get`,
            url : `${API}/carts`,
            headers: {
            Authorization: `Bearer ${token}`,
            },
        });
        carts = res_cart.data.cart;
    
        const res_notifications = await axios({
            method: `get`,
            url: `${API}/orders/notification`,
            headers: {
            Authorization: `Bearer ${token}`,
            },
        });
        notifications = res_notifications.data.notif;
    
        
    } catch (error) {
        console.log(error.response);
    }
    

    return {
        props: {
            carts,
            notifications,
            user,
            token
        },
    };
}

function Notifications({carts, notifications, user, token}) { 
    let cartLength = 0;
        carts.map((data)=>{
        cartLength+=data.product_cart.length
    })

    return (
        <>
        <Head>
            <title>Notifications</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <script
                src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                crossOrigin="anonymous"
            ></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        </Head>

        <MobileLayout user={user} cartLength={cartLength} notifications={notifications}>
        <h5 className="ms-4 mt-2">Notifications</h5>
        {notifications.map((notification, index) => (
        <div className="px-2 py-1">
            {notification.mark_as_read == false ? (
                <div className="d-flex gap-2 p-2" key={index} style={{backgroundColor:"#f1d7fc"}} >
                    <Link href={`${notification.notification_link}`}>
                        <a  className="text-decoration-none" style={{color: "black"}}>
                        <div style={{width:"100%"}}>
                            <div className="d-flex" style={{ fontSize: "0.8rem", color: "black", fontWeight: "700" }}>
                                <i className="bi bi-cart-check"></i>
                                <div className="ms-2">Order Produk</div>
                                <p className="ms-auto">
                                    {moment(notification.createdAt).format("DD MMM, hh.mm")}
                                </p>    
                            </div>
                            <div>
                                <h6 className="m-0">{notification.notification_title}</h6>
                                <p className="m-0 mt-1">{notification.notification_desc}</p>
                                <hr className="m-0 mt-3"/>
                            </div>
                        </div>
                        </a>
                    </Link>
                </div>
            ):(
                <div className="d-flex  gap-2 me-2 p-2" key={index}>
                    <Link href={`${notification.notification_link}`}>
                        <a  className="text-decoration-none" style={{color: "black"}}>
                            <div style={{width:"100%"}}>
                                <div className="d-flex" style={{ fontSize: "0.8rem", color: "black", fontWeight: "700" }}>
                                    <i class="bi bi-cart-check"></i>
                                    <div className="ms-2">Order Produk</div>
                                        <p className="ms-auto">
                                        {moment(notification.createdAt).format(
                                            "DD MMM, hh.mm"
                                        )}
                                        </p>
                                    </div>
                                <div>
                                    <h6 className="m-0">{notification.notification_title}</h6>
                                    <p className="m-0 mt-1">{notification.notification_desc}</p>
                                    <hr className="m-0 mt-3"/>
                                </div>
                            </div>
                        </a>
                    </Link>
                </div>
            )}
        </div>
        ))}
        </MobileLayout>
    </>
    );
}

export default Notifications;
