/* eslint-disable @next/next/no-sync-scripts */
import axios from "axios";
import Head from "next/head";
import MainLayout from "../layout/mainLayout";
import useResize from "../hooks/useResize";
import ButtonMasuk from "../components/buttonMasuk";
import CategoryLayout from "../layout/categoryLayout";
import CategoryLayoutMobile from "../layout/categoryLayoutMobile";
import { useRouter } from "next/router";
import { GetToken } from "../utils/getToken";
import { useEffect } from "react";
import MobileLayout from "../layout/mobileLayout";

export async function getServerSideProps({ req, res }) {
  const API = process.env.NEXT_PUBLIC_API_ENDPOINT;

  let user = null;
  let allcookie = req.headers.cookie || "   ";
  let token = GetToken(allcookie);
  let products = [];
  let products_sayur = [];
  let products_buah = [];
  let products_rempah = [];
  let carts = [];
  let notifications = []

  try {
    const res_products = await axios.get(API +"/products");
    products = res_products.data.data;

    const res_products_sayur = await axios.get(API + "/products/categories/1");
    products_sayur = res_products_sayur.data.data;

    const res_products_buah = await axios.get(
      API + "/products/categories/2"
    );
    products_buah = res_products_buah.data.data;

    const res_products_rempah = await axios.get(API + "/products/categories/3");
    products_rempah = res_products_rempah.data.data;

    const res_user = await axios({
      method: `get`,
      url: `${API}/users`,
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
    user = res_user.data.data;

    const res_cart = await axios({
      method: `get`,
      url : `${API}/carts`,
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
    carts = res_cart.data.cart;

    const res_notifications = await axios({
      method: `get`,
      url: `${API}/orders/notification`,
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
    notifications = res_notifications.data.notif;

    
  } catch (error) {
    console.log(error.response);
  }

  return {
    props: {
      user,
      token,
      products,
      products_sayur,
      products_buah,
      products_rempah,
      carts,
      notifications,
    },
  };
}

export default function Home({
  user,
  token,
  products,
  products_sayur,
  products_buah,
  products_rempah,
  carts,
  notifications,
}) {
  const screen = useResize();
  const router = useRouter();

  // console.log(notifications);
  //hitung cart
  let cartLength = 0;
  carts.map((data)=>{
    cartLength+=data.product_cart.length
  })
  
  useEffect(() => {
    if (user != null && user.role_id == 1) {
      router.replace("/seller");
    }
  });

  return (
    <>
      <Head>
        <title>Rumah Tani</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossOrigin="anonymous"
        ></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
      </Head>

      {screen.md ? (
        <MainLayout user={user} cartLength={cartLength} notifications={notifications}>
          <div className="row">
            <div className="col-10 offset-1 mt-5 d-none d-sm-block">
              <div
                id="carouselExampleControls"
                className="carousel slide"
                data-bs-ride="carousel"
              >
                <div className="carousel-inner">
                  <div className="carousel-item active">
                    <img src="/banner.png" className="d-flex w-100" alt="..." />
                  </div>
                  <div className="carousel-item">
                    <img src="/banner.png" className="d-flex w-100" alt="..." />
                  </div>
                  <div className="carousel-item">
                    <img src="/banner.png" className="d-flex w-100" alt="..." />
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="row">
            <div className="col-10 offset-1 mt-5 fs-5">
              <CategoryLayout
                user={user}
                products={products}
                products_sayur={products_sayur}
                products_buah={products_buah}
                products_rempah={products_rempah}
              />
            </div>
          </div>
        </MainLayout>
      ) : (
        <MobileLayout user={user} cartLength={cartLength}>
          <div className="banner mb-4">
            <div className="container-fluid px-0 mb-0 mt-0">
              <div className="row pt-5 pb-2 ps-4">
                <div className="col-7">
                  <p className="fs-2 fw-bold">
                    Bulan Kemerdekaan <br />
                    Banyak Diskon!
                  </p>

                  <h6>Diskon Hingga</h6>
                  <div className="mb-4">
                    <span className="fs-2 text-danger ms-2">60%</span>
                    <span className="fs-2 text-danger ms-4"><img src="/hut77.png" style={{width:"50px"}}/></span>
                  </div>
                  
                </div>
                <div className="col-5">
                  <img src="/cart.png" />
                </div>
              </div>

              <div className="offcanvas offcanvas-start" id="demo">
                <div className="offcanvas-header">
                  <strong className="offcanvas-title fs-4">Rumah Tani</strong>
                  <button
                    type="button"
                    className="btn-close"
                    data-bs-dismiss="offcanvas"
                  ></button>
                </div>
                <div className="offcanvas-body">
                  <a href="/account/login" className="text-decoration-none">
                    <ButtonMasuk />
                  </a>
                </div>
              </div>
            </div>
          </div>
          <CategoryLayoutMobile
            user={user}
            products={products}
            products_sayur={products_sayur}
            products_buah={products_buah}
            products_rempah={products_rempah}
          />
        </MobileLayout>
      )}
    </>
  );
}
