/* eslint-disable @next/next/no-html-link-for-pages */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @next/next/no-sync-scripts */
import Head from "next/head";
import Top from "../../components/top";
import styles from "../../styles/Home.module.css";

export default function InfoProfile() {
  return (
    <>
      <Head>
        <title>Info Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossorigin="anonymous"
        ></script>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
      </Head>

      <Top>
        <h4 className="mx-auto">Lengkapi Info Akun</h4>

      </Top>

      <div className="container">
        <div className="row">
          <i className="bi bi-arrow-left fs-2 mt-2"></i>
          <div className="col-md-4 offset-md-4">
            <div className="mt-4 d-flex justify-content-center">
              <img src="/kamera.png" />
            </div>
            <div className="login-form mt-4 ">
              <form action="" method="" className="row g-3">
                <div className={styles.InfoAkun}>
                  <div className="col-12 mt-2">
                    <label>Nama*</label>
                    <input
                      type="text"
                      name="username"
                      className="form-control"
                      placeholder="Nama"
                    />
                  </div>
                  <div className="col-12 mt-2">
                    <label>Kota*</label>
                    <select
                      className="form-select"
                      aria-label="Default select example"
                    >
                      <option value="">Pilih Kota</option>
                      <option value="1">One</option>
                      <option value="2">Two</option>
                      <option value="3">Three</option>
                    </select>
                  </div>
                  <div className="col-12 mt-2">
                    <label>Alamat*</label>
                    <textarea
                      className="form-control"
                      id="exampleFormControlTextarea1"
                      rows="2"
                      placeholder="Contoh: Jalan Ikan Hiu 33"
                    ></textarea>
                  </div>
                  <div className="col-12 mt-2">
                    <label>No Handphone*</label>
                    <input
                      type="text"
                      name="username"
                      className="form-control"
                      placeholder="contoh: +628123456789"
                    />
                  </div>
                  <div className="col-12 mt-3 mb-3">
                    <button
                      type="submit"
                      name="username"
                      className="form-control"
                    >
                      Simpan
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
