/* eslint-disable @next/next/no-html-link-for-pages */
/* eslint-disable react/no-unknown-property */
/* eslint-disable @next/next/no-sync-scripts */
import React from "react";
import Head from "next/head";
import UpdateProdukLayout from "../../layout/updateprodukForm";
import Top from "../../components/top";
import useResize from "../../hooks/useResize";

export default function AddProduk() {
  const screen = useResize();
  return (
    <>
      <Head>
        <title>Update Produk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossorigin="anonymous"
        ></script>
      </Head>

      {screen.md ? (
        <Top />
      ) : (
        <div className="d-flex d-row gap-2 m-3 fw-bold fs-4 justify-content-center">
          <i className="bi bi-arrow-left pe-3"></i>
          <p className="">Lengkapi Detail Produk</p>
        </div>
      )}

      {screen.md ? (
        <div className="col-6 offset-3 mt-3 d-flex flex-column justify-content-center">
          <i className="bi bi-arrow-left fs-3 mt-2"></i>

          <UpdateProdukLayout />
        </div>
      ) : (
        <div className="px-3">
          <UpdateProdukLayout />
        </div>
      )}
    </>
  );
}
